//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelotaEnlaceDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEstadisticaEntities : DbContext
    {
        public DbEstadisticaEntities()
            : base("name=DbEstadisticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Equipos> Equipos { get; set; }
        public DbSet<Juegos> Juegos { get; set; }
        public DbSet<Jugadores> Jugadores { get; set; }
        public DbSet<Posiciones> Posiciones { get; set; }
        public DbSet<TipoEstadisticas> TipoEstadisticas { get; set; }
        public DbSet<Ligas> Ligas { get; set; }
    }
}
