//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelotaEnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public Equipos()
        {
            this.Jugadores = new HashSet<Jugadores>();
            this.Juegos = new HashSet<Juegos>();
            this.Juegos1 = new HashSet<Juegos>();
            this.Juegos2 = new HashSet<Juegos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Jugadores> Jugadores { get; set; }
        public virtual ICollection<Juegos> Juegos { get; set; }
        public virtual ICollection<Juegos> Juegos1 { get; set; }
        public virtual ICollection<Juegos> Juegos2 { get; set; }
    }
}
