//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelotaEnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public Equipos()
        {
            this.Jugadores = new HashSet<Jugadores>();
            this.Juegos = new HashSet<Juegos>();
            this.Juegos1 = new HashSet<Juegos>();
            this.Juegos2 = new HashSet<Juegos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Jugadores> Jugadores { get; set; }
        public virtual ICollection<Juegos> Juegos { get; set; }
        public virtual ICollection<Juegos> Juegos1 { get; set; }
        public virtual ICollection<Juegos> Juegos2 { get; set; }
    }
}
