//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelotaEnlaceDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstadisticaDbEntities : DbContext
    {
        public EstadisticaDbEntities()
            : base("name=EstadisticaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Equipos> Equipos { get; set; }
        public DbSet<Juegos> Juegos { get; set; }
        public DbSet<Jugadores> Jugadores { get; set; }
        public DbSet<Ligas> Ligas { get; set; }
        public DbSet<Posiciones> Posiciones { get; set; }
        public DbSet<TipoEstadisticas> TipoEstadisticas { get; set; }
    }
}
