//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelotaEnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posiciones
    {
        public Posiciones()
        {
            this.Jugadores = new HashSet<Jugadores>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Jugadores> Jugadores { get; set; }
    }
}
