//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelotaEnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEstadisticas
    {
        public int Id { get; set; }
        public Nullable<double> Promedio { get; set; }
        public Nullable<double> SLG { get; set; }
        public Nullable<int> JugadorID { get; set; }
    
        public virtual Jugadores Jugadores { get; set; }
    }
}
