//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelotaEnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEstadisticas
    {
        public int Id { get; set; }
        public Nullable<double> Promedio { get; set; }
        public Nullable<double> SLG { get; set; }
        public Nullable<int> JugadorID { get; set; }
    
        public virtual Jugadores Jugadores { get; set; }
    }
}
