//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelota.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego
    {
        public int Id { get; set; }
        public string NumeroJuego { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> Equipo1 { get; set; }
        public Nullable<int> Equipo2 { get; set; }
        public Nullable<int> Ganador { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo3 { get; set; }
        public virtual Equipo Equipo4 { get; set; }
    }
}
