//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelota.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloEntityContainer : DbContext
    {
        public ModeloEntityContainer()
            : base("name=ModeloEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Juego> Juegos { get; set; }
        public DbSet<Equipo> Equipoes { get; set; }
        public DbSet<Jugador> Jugadors { get; set; }
        public DbSet<Liga> Ligas { get; set; }
        public DbSet<Posicione> Posiciones { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TipoEstadistica> TipoEstadisticas { get; set; }
    }
}
