//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadisticaPelota.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEstadistica
    {
        public int Id { get; set; }
        public string Promedio { get; set; }
        public int EquipoId { get; set; }
        public string SLG { get; set; }
        public int JugadorId { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
